[build-system]
requires = ["maturin>=1.12.0,<2.0"]
build-backend = "maturin"

[project]
name = "obstore-databaas"
requires-python = ">=3.10"
readme = "README.md"
dependencies = ["typing-extensions; python_version < '3.13'"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Framework :: FastAPI",
    "Framework :: aiohttp",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Internet",
    "Typing :: Typed",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "obstore._obstore"
python-source = "python"
